spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/statefin_prod}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ERROR
    kg.infosystems: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
  file:
    name: /var/log/statefin/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

jwt:
  secret: ${JWT_SECRET}

app:
  initial-data:
    load-on-startup: ${LOAD_INITIAL_DATA:false}