spring:
  application:
    name: statefin-user-management
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    kg.infosystems: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.zaxxer.hikari: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:MySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm}
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  
  initial-data:
    load-on-startup: true
    admin:
      username: ${ADMIN_USERNAME:admin}
      email: ${ADMIN_EMAIL:admin@statefin.com}
      password: ${ADMIN_PASSWORD:Admin123!}
    user:
      username: ${USER_USERNAME:user}
      email: ${USER_EMAIL:user@demo.com}
      password: ${USER_PASSWORD:User123!}
    manager:
      username: ${MANAGER_USERNAME:manager}
      email: ${MANAGER_EMAIL:manager@demo.com}
      password: ${MANAGER_PASSWORD:Manager123!}