spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: WARN
    kg.infosystems: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN

app:
  initial-data:
    load-on-startup: true